#2018-2019 Programação II (LTI)
#Grupo 02
#51893 Miguel Alexandre Almeida
#53311 José Carlos Aurora da Costa Silva Ferreira

### HEADER INDEX ###
HEADER_LINES=7 #Number of lines in the header
HEADER_HOURS=3 
HEADER_FILETYPE=6
HEADER_DATE=1

### CLIENT HEADER INDEX ###
CL_NAME=0
CL_LOCAL=1
CL_SERVICE_DATE=2
CL_SERVICE_HOUR=3
CL_MAX_PRICE=4
CL_SERVICE_REP=5
CL_SERVICE_DOM=6
CL_SERVICE_TIME=7

### EXPERT HEADER INDEX ###
XPRT_NAME=0
XPRT_LOCAL=1
XPRT_DOM=2
XPRT_REP=3
XPRT_PRICE=4
XPRT_LASTJOB_DATE=5
XPRT_LASTJOB_HOUR=6
XPRT_CUMVALUE=7

### SCHEDULE HEADER INDEX ###
SCHD_DATE=0
SCHD_HOUR=1
SCHD_CL=2
SCHD_XPRT=3
